/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: .sanity/schema.json
export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: BilingualSlug;
  publishedAt?: string;
  author?: AuthorReference;
  category?: CategoryReference;
  excerpt?: LocaleText;
  coverImage?: ImageWithAlt;
  body?: LocaleBlocks;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: LocaleString;
  description?: LocaleString;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LocaleBlocks = {
  _type: "localeBlocks";
  nl?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
  >;
  en?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          newTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
  >;
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: LocaleString;
  caption?: LocaleString;
};

export type LocaleText = {
  _type: "localeText";
  nl?: string;
  en?: string;
};

export type BilingualSlug = {
  _type: "bilingualSlug";
  nl?: Slug;
  en?: Slug;
};

export type LocaleString = {
  _type: "localeString";
  nl?: string;
  en?: string;
};

export type ConceptReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "concept";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type Case = {
  _id: string;
  _type: "case";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: "events" | "in-company";
  title?: LocaleString;
  slug?: BilingualSlug;
  client?: string;
  eventDate?: string;
  location?: string;
  guestCount?: number;
  conceptsUsed?: Array<
    {
      _key: string;
    } & ConceptReference
  >;
  hero?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  testimonial?: TestimonialReference;
  story?: LocaleBlocks;
  seo?: Seo;
};

export type PricingTier = {
  _id: string;
  _type: "pricingTier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  concept?: ConceptReference;
  basePriceCents?: number;
  pricePerGuestCents?: number;
  minGuests?: number;
  maxGuests?: number;
  durationHours?: number;
};

export type Concept = {
  _id: string;
  _type: "concept";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: "events" | "in-company";
  title?: LocaleString;
  slug?: BilingualSlug;
  shortDescription?: LocaleText;
  hero?: ImageWithAlt;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  body?: LocaleBlocks;
  specs?: Array<{
    label?: LocaleString;
    value?: LocaleString;
    _type: "spec";
    _key: string;
  }>;
  seo?: Seo;
};

export type BrandingOption = {
  _id: string;
  _type: "brandingOption";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  description?: LocaleText;
  image?: ImageWithAlt;
  priceModifierCents?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: LocaleText;
  author?: string;
  role?: LocaleString;
  company?: string;
  avatar?: ImageWithAlt;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: BilingualSlug;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: LocaleString;
  bio?: LocaleText;
  avatar?: ImageWithAlt;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocaleString;
  slug?: {
    nl?: Slug;
    en?: Slug;
  };
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contactInfo?: {
    email?: string;
    phone?: string;
    address?: string;
  };
  social?: {
    instagram?: string;
    linkedin?: string;
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageAssetReference
  | Seo
  | LocaleBlocks
  | ImageWithAlt
  | LocaleText
  | BilingualSlug
  | LocaleString
  | ConceptReference
  | TestimonialReference
  | Case
  | PricingTier
  | Concept
  | BrandingOption
  | Testimonial
  | Category
  | Author
  | Page
  | Slug
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries/case.ts
// Variable: CASES_QUERY
// Query: *[_type == "case" && (!defined($category) || category == $category)] | order(eventDate desc) {    _id,    category,    title,    slug,    client,    eventDate,    location,    guestCount,    "hero": { "url": hero.asset->url, "alt": hero.alt }  }
export type CASES_QUERY_RESULT = Array<{
  _id: string;
  category: "events" | "in-company" | null;
  title: LocaleString | null;
  slug: BilingualSlug | null;
  client: string | null;
  eventDate: string | null;
  location: string | null;
  guestCount: number | null;
  hero: {
    url: string | null;
    alt: LocaleString | null;
  };
}>;

// Source: src/lib/sanity/queries/case.ts
// Variable: CASE_BY_SLUG_QUERY
// Query: *[_type == "case" && slug[$locale].current == $slug][0] {    _id,    category,    title,    slug,    client,    eventDate,    location,    guestCount,    hero { ..., "url": asset->url },    gallery[] { ..., "url": asset->url },    "conceptsUsed": conceptsUsed[]-> { _id, title, slug, category },    "testimonial": testimonial-> { quote, author, role, company },    story,    seo  }
export type CASE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  category: "events" | "in-company" | null;
  title: LocaleString | null;
  slug: BilingualSlug | null;
  client: string | null;
  eventDate: string | null;
  location: string | null;
  guestCount: number | null;
  hero: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    caption?: LocaleString;
    url: string | null;
  } | null;
  gallery: Array<{
    _key: string;
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    caption?: LocaleString;
    url: string | null;
  }> | null;
  conceptsUsed: Array<{
    _id: string;
    title: LocaleString | null;
    slug: BilingualSlug | null;
    category: "events" | "in-company" | null;
  }> | null;
  testimonial: {
    quote: LocaleText | null;
    author: string | null;
    role: LocaleString | null;
    company: string | null;
  } | null;
  story: LocaleBlocks | null;
  seo: Seo | null;
} | null;

// Source: src/lib/sanity/queries/concept.ts
// Variable: CONCEPTS_QUERY
// Query: *[_type == "concept" && (!defined($category) || category == $category)] | order(title.nl asc) {    _id,    category,    title,    slug,    shortDescription,    "hero": { "url": hero.asset->url, "alt": hero.alt }  }
export type CONCEPTS_QUERY_RESULT = Array<{
  _id: string;
  category: "events" | "in-company" | null;
  title: LocaleString | null;
  slug: BilingualSlug | null;
  shortDescription: LocaleText | null;
  hero: {
    url: string | null;
    alt: LocaleString | null;
  };
}>;

// Source: src/lib/sanity/queries/concept.ts
// Variable: CONCEPT_BY_SLUG_QUERY
// Query: *[_type == "concept" && slug[$locale].current == $slug][0] {    _id,    category,    title,    slug,    shortDescription,    hero { ..., "url": asset->url },    gallery[] { ..., "url": asset->url },    body,    specs,    seo  }
export type CONCEPT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  category: "events" | "in-company" | null;
  title: LocaleString | null;
  slug: BilingualSlug | null;
  shortDescription: LocaleText | null;
  hero: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    caption?: LocaleString;
    url: string | null;
  } | null;
  gallery: Array<{
    _key: string;
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    caption?: LocaleString;
    url: string | null;
  }> | null;
  body: LocaleBlocks | null;
  specs: Array<{
    label?: LocaleString;
    value?: LocaleString;
    _type: "spec";
    _key: string;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/lib/sanity/queries/post.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && publishedAt <= now()] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt,    excerpt,    "author": author-> { name, "avatar": avatar.asset->url },    "category": category-> { title, slug },    "coverImage": { "url": coverImage.asset->url, "alt": coverImage.alt }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: LocaleString | null;
  slug: BilingualSlug | null;
  publishedAt: string | null;
  excerpt: LocaleText | null;
  author: {
    name: string | null;
    avatar: string | null;
  } | null;
  category: {
    title: LocaleString | null;
    slug: BilingualSlug | null;
  } | null;
  coverImage: {
    url: string | null;
    alt: LocaleString | null;
  };
}>;

// Source: src/lib/sanity/queries/post.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug[$locale].current == $slug && publishedAt <= now()][0] {    _id,    title,    slug,    publishedAt,    excerpt,    body,    coverImage { ..., "url": asset->url },    "author": author-> { name, role, bio, "avatar": avatar.asset->url },    "category": category-> { title, slug },    seo  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: LocaleString | null;
  slug: BilingualSlug | null;
  publishedAt: string | null;
  excerpt: LocaleText | null;
  body: LocaleBlocks | null;
  coverImage: {
    _type: "imageWithAlt";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocaleString;
    caption?: LocaleString;
    url: string | null;
  } | null;
  author: {
    name: string | null;
    role: LocaleString | null;
    bio: LocaleText | null;
    avatar: string | null;
  } | null;
  category: {
    title: LocaleString | null;
    slug: BilingualSlug | null;
  } | null;
  seo: Seo | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "case" && (!defined($category) || category == $category)] | order(eventDate desc) {\n    _id,\n    category,\n    title,\n    slug,\n    client,\n    eventDate,\n    location,\n    guestCount,\n    "hero": { "url": hero.asset->url, "alt": hero.alt }\n  }\n': CASES_QUERY_RESULT;
    '\n  *[_type == "case" && slug[$locale].current == $slug][0] {\n    _id,\n    category,\n    title,\n    slug,\n    client,\n    eventDate,\n    location,\n    guestCount,\n    hero { ..., "url": asset->url },\n    gallery[] { ..., "url": asset->url },\n    "conceptsUsed": conceptsUsed[]-> { _id, title, slug, category },\n    "testimonial": testimonial-> { quote, author, role, company },\n    story,\n    seo\n  }\n': CASE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "concept" && (!defined($category) || category == $category)] | order(title.nl asc) {\n    _id,\n    category,\n    title,\n    slug,\n    shortDescription,\n    "hero": { "url": hero.asset->url, "alt": hero.alt }\n  }\n': CONCEPTS_QUERY_RESULT;
    '\n  *[_type == "concept" && slug[$locale].current == $slug][0] {\n    _id,\n    category,\n    title,\n    slug,\n    shortDescription,\n    hero { ..., "url": asset->url },\n    gallery[] { ..., "url": asset->url },\n    body,\n    specs,\n    seo\n  }\n': CONCEPT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && publishedAt <= now()] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    "author": author-> { name, "avatar": avatar.asset->url },\n    "category": category-> { title, slug },\n    "coverImage": { "url": coverImage.asset->url, "alt": coverImage.alt }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug[$locale].current == $slug && publishedAt <= now()][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    body,\n    coverImage { ..., "url": asset->url },\n    "author": author-> { name, role, bio, "avatar": avatar.asset->url },\n    "category": category-> { title, slug },\n    seo\n  }\n': POST_BY_SLUG_QUERY_RESULT;
  }
}
